// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

/*
Package examples is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	In
	Out
*/
package examples

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type In struct {
	Input string `protobuf:"bytes,1,opt,name=input" json:"input,omitempty"`
}

func (m *In) Reset()                    { *m = In{} }
func (m *In) String() string            { return proto.CompactTextString(m) }
func (*In) ProtoMessage()               {}
func (*In) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *In) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

type Out struct {
	Output string `protobuf:"bytes,1,opt,name=output" json:"output,omitempty"`
}

func (m *Out) Reset()                    { *m = Out{} }
func (m *Out) String() string            { return proto.CompactTextString(m) }
func (*Out) ProtoMessage()               {}
func (*Out) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Out) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func init() {
	proto.RegisterType((*In)(nil), "examples.In")
	proto.RegisterType((*Out)(nil), "examples.Out")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 124 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x48, 0xad, 0x48, 0xcc, 0x2d,
	0xc8, 0x49, 0x2d, 0x56, 0x92, 0xe2, 0x62, 0xf2, 0xcc, 0x13, 0x12, 0xe1, 0x62, 0xcd, 0xcc, 0x2b,
	0x28, 0x2d, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x94, 0x64, 0xb9, 0x98, 0xfd,
	0x4b, 0x4b, 0x84, 0xc4, 0xb8, 0xd8, 0xf2, 0x4b, 0x4b, 0x10, 0xb2, 0x50, 0x9e, 0x91, 0x36, 0x17,
	0x73, 0x50, 0x80, 0xb3, 0x90, 0x0a, 0x17, 0xab, 0x67, 0x1e, 0x48, 0x1d, 0x8f, 0x1e, 0xcc, 0x54,
	0x3d, 0xcf, 0x3c, 0x29, 0x5e, 0x04, 0xcf, 0xbf, 0xb4, 0x24, 0x89, 0x0d, 0x6c, 0xb1, 0x31, 0x20,
	0x00, 0x00, 0xff, 0xff, 0x3c, 0x44, 0xcc, 0x34, 0x89, 0x00, 0x00, 0x00,
}
